zone                    = "europe-west4-a"
image_family            = "ubuntu-2004-ghr-nvidia"
source_image            = "ubuntu-2004-focal-v20220419"
source_image_project_id = "ubuntu-os-cloud"
machine_type            = "a2-highgpu-1g"
nvidia_major_version    = "510"
