source_image            = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20240614"
instance_type           = "t4g.micro"
arch                    = "arm64"
script                  = "setup_without_nvidia.sh"
nvidia_major_version    = ""
image_owner             = "099720109477"
gr_oss_image_name       = "gross-cuda-nvidia-ghrunner"