variable "region" { type = string }
variable "source_image" { type = string }
variable "instance_type" { type = string }
variable "runner_version" { type = string }
variable "arch" { type=string }
variable "nvidia_major_version" { type = string }
variable "script" { type = string }
variable "image_owner" { type = string }
variable "gr_oss_image_name" { type = string }