source_image            = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211129"
instance_type           = "g4dn.xlarge"
arch                    = "amd64"
nvidia_major_version    = "510"
script                  = "setup_with_nvidia.sh"