source_image            = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220420"
instance_type           = "t2.medium"
arch                    = "amd64"
nvidia_major_version    = "510"
script                  = "setup_without_nvidia.sh"
image_owner             = "099720109477"
gr_oss_image_name       = "gross-release-without-nvidia-ghrunner"