name: Packer Lint for AWS

on:
  pull_request:
  push:
  workflow_call:

jobs:
  validate-aws:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - params: {"aws-region": "us-east-1", "arch": "amd64"}
          - params: {"aws-region": "us-east-1", "arch": "arm64"}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init ./aws

      - name: Validate Template:AWS
        run: |
          packer validate -var-file=./aws/${{ matrix.params.arch }}/values.pkrvars.hcl -var "region=${{ matrix.params.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws
