name: Packer Build for AWS

on:
  workflow_dispatch:

jobs:
  build-aws-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    # environment: aws_dev
    strategy:
      matrix:
        aws-region: [us-east-1, us-west-2]
        environment: [ 'dev1', 'dev2' ]
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init ./aws

      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Image:AWS
        run: |
          packer build -force -var-file=./aws/amd64/values.pkrvars.hcl -var "region=${{ matrix.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws
          packer build -force -var-file=./aws/arm64/values.pkrvars.hcl -var "region=${{ matrix.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws

  build-aws-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    environment: aws_prod
    strategy:
      matrix:
        aws-region: [us-east-1, us-west-2]
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init ./aws

      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Image:AWS
        run: |
          packer build -force -var-file=./aws/amd64/values.pkrvars.hcl -var "region=${{ matrix.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws
          packer build -force -var-file=./aws/arm64/values.pkrvars.hcl -var "region=${{ matrix.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws