name: Packer Lint for AWS

on:
  pull_request:
  push:
  workflow_call:

jobs:
  validate-aws:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        aws-region: [us-east-1, us-west-2]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init ./aws

      - name: Validate Template:AWS
        run: |
          packer validate -var-file=./aws/amd64/values.pkrvars.hcl -var "region=${{ matrix.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws
          packer validate -var-file=./aws/arm64/values.pkrvars.hcl -var "region=${{ matrix.aws-region }}" -var "runner_version=$(cat versions.json | jq -r '.runner')" ./aws