name: Packer Lint for GCP

on:
  pull_request:
  push:
  workflow_call:

jobs:
  validate-gcp:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries:GCP
        run: packer init ./gcp

      - name: Validate Template:GCP
        env:
          PKR_VAR_project: dummy_value
        run: packer validate -var-file=./gcp/amd64/values.pkrvars.hcl -var "runner_version=$(cat versions.json | jq -r '.runner')" ./gcp